version: 0.3.{build}
skip_tags: true
os: MinGW
platform:
  - x86
  - x64
clone_depth: 1
build_script:
- make Makefile
test_script:
- make test
notifications:
- provider: Email
  to:
  - rurban@x-ray.at
  subject: potion windows build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false