/* A recursive-descent parser generated by greg 0.4.6 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 38

# include "greg.h"

# include <unistd.h>
# include <libgen.h>
# include <assert.h>

  typedef struct Header Header;

  struct Header {
    char   *text;
    Header *next;
  };

  int   verboseFlag= 0;

  static char	*trailer= 0;
  static Header	*headers= 0;
  static char   *deftrailer= "\n\
#ifdef YY_MAIN\n\
int main()\n\
{\n\
  GREG g;\n\
  yyinit(&g);\n\
  while (yyparse(&g));\n\
  yydeinit(&g);\n\
  return 0;\n\
}\n\
#endif\n\
";

  void makeHeader(char *text);
  void makeTrailer(char *text);

#ifndef YY_ALLOC
#define YY_ALLOC(N, D) malloc(N)
#endif
#ifndef YY_CALLOC
#define YY_CALLOC(N, S, D) calloc(N, S)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(B, N, D) realloc(B, N)
#endif
#ifndef YY_FREE
#define YY_FREE free
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YY_NAME
#define YY_NAME(N) yy##N
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= fgetc(G->input);				\
    if ('\n' == yyc) ++G->lineno;      		\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintfv((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_ERROR
#define YY_ERROR(message) yyerror(G, message)
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( G->begin= G->pos, 1)
#endif
#ifndef YY_END
#define YY_END		( G->end= G->pos, 1)
#endif
#ifdef YY_DEBUG
# define yydebug G->debug
# ifndef YYDEBUG_PARSE
#  define YYDEBUG_PARSE   1
# endif
# ifndef YYDEBUG_VERBOSE
#  define YYDEBUG_VERBOSE 2
# endif
# define yyprintf(args)	   if (yydebug & YYDEBUG_PARSE)   fprintf args
# define yyprintfv(args)   if (yydebug & YYDEBUG_VERBOSE) fprintf args
# define yyprintfGcontext  if (yydebug & YYDEBUG_PARSE)   yyprintcontext(G,stderr,G->buf+G->pos)
# define yyprintfvGcontext if (yydebug & YYDEBUG_VERBOSE) yyprintcontext(G,stderr,G->buf+G->pos)
# define yyprintfvTcontext(text) if (yydebug & YYDEBUG_VERBOSE) yyprintcontext(G,stderr,text)
# define yyprintfokrule(rule) if (yydebug & YYDEBUG_PARSE) {\
  if (G->buf[G->pos]) {\
    fprintf(stderr, "  ok   %s", rule);\
    yyprintcontext(G,stderr,G->buf+G->pos);\
    fprintf(stderr, "\n");\
  } else {\
    yyprintfv((stderr, "  ok   %s @ \"\"\n", rule));\
  }}
# define yyprintfvokrule(rule) if (yydebug & YYDEBUG_VERBOSE) {\
  if (G->buf[G->pos]) {\
    fprintf(stderr, "  ok   %s", rule);\
    yyprintcontext(G,stderr,G->buf+G->pos);\
    fprintf(stderr, "\n");\
  } else {\
    yyprintfv((stderr, "  ok   %s @ \"\"\n", rule));\
  }}
# define yyprintfvfailrule(rule) if (yydebug & YYDEBUG_VERBOSE) {\
    fprintf(stderr, "  fail %s", rule);\
    yyprintcontext(G,stderr,G->buf+G->pos);\
    fprintf(stderr, "\n");\
  }
#else
# define yydebug 0
# define yyprintf(args)
# define yyprintfv(args)
# define yyprintfGcontext
# define yyprintfvGcontext
# define yyprintfvTcontext(text)
# define yyprintfokrule(rule)
# define yyprintfvokrule(rule)
# define yyprintfvfailrule(rule)
#endif
#ifndef YY_XVAR
#define YY_XVAR yyxvar
#endif

#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 1024
#endif

#ifndef YY_BUFFER_START_SIZE
#define YY_BUFFER_START_SIZE 16384
#endif

#ifndef YY_PART
#define yydata G->data
#define yy G->ss

typedef void (*yyaction)(struct _GREG *G, char *yytext, int yyleng, struct _yythunk *thunkpos, YY_XTYPE YY_XVAR);
typedef struct _yythunk { int begin, end;  yyaction  action; const char *name; struct _yythunk *next; } yythunk;


YY_LOCAL(int) yyrefill(GREG *G)
{
  int yyn;
  while (G->buflen - G->pos < 512) {
    G->buflen *= 2;
    G->buf= (char*)YY_REALLOC(G->buf, G->buflen, G->data);
  }
  YY_INPUT((G->buf + G->pos), yyn, (G->buflen - G->pos));
  if (!yyn) return 0;
  G->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(GREG *G)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  ++G->pos;
  return 1;
}

#ifdef YY_DEBUG
YY_LOCAL(char *) yycontextline(struct _GREG *G, char *s)
{
  char *context = s;
  char *nl = strchr(context, 10);
  if (nl) {
    context = (char*)YY_ALLOC(nl-s+1, G->data);
    strncpy(context, s, nl-s);
    context[nl-s] = '\0'; /* replace nl by 0 */
    return context;
  } else return NULL;
}
YY_LOCAL(void) yyprintcontext(struct _GREG *G, FILE *stream, char *s)
{
  char *context = yycontextline(G, s);
  if (context) {
    fprintf(stream, " @ \"%s\"", context);
    YY_FREE(context);
  }
}
#endif

YY_LOCAL(void) yyerror(struct _GREG *G, char *message)
{
  fputs(message, stderr);
  if (G->text[0]) fprintf(stderr, " near token '%s'", G->text);
  if (G->pos < G->limit || !feof(G->input)) {
      G->buf[G->limit]= '\0';
      fprintf(stderr, " before text \"");
      while (G->pos < G->limit) {
	if ('\n' == G->buf[G->pos] || '\r' == G->buf[G->pos]) break;
	fputc(G->buf[G->pos++], stderr);
      }
      if (G->pos == G->limit) {
	int c;
	while (EOF != (c= fgetc(G->input)) && '\n' != c && '\r' != c)
	  fputc(c, stderr);
      }
      fputc('\"', stderr);
  }
  fprintf(stderr, " at %s:%d\n", G->filename, G->lineno);
  exit(1);
}

YY_LOCAL(int) yymatchChar(GREG *G, int c)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  if ((unsigned char)G->buf[G->pos] == c) {
#ifdef YY_DEBUG
    if (c) {
      if (c<32) { yyprintfv((stderr, "  ok   yymatchChar '0x%x'", c));}
      else      { yyprintfv((stderr, "  ok   yymatchChar '%c'", c));}
      yyprintfvGcontext;
      yyprintfv((stderr, "\n"));
    } else {
      yyprintfv((stderr, "  ok   yymatchChar '0x0' @ \"\"\n"));
    }
#endif
    ++G->pos;
    return 1;
  }
  if (c<32) { yyprintfv((stderr, "  fail yymatchChar '0x%x'", c));}
  else      { yyprintfv((stderr, "  fail yymatchChar '%c'", c));}
  yyprintfvGcontext;
  yyprintfv((stderr, "\n"));
  return 0;
}

YY_LOCAL(int) yymatchString(GREG *G, const char *s)
{
  int yysav= G->pos;
  while (*s) {
    if (G->pos >= G->limit && !yyrefill(G)) return 0;
    if (G->buf[G->pos] != *s) {
      G->pos= yysav;
      return 0;
    }
    ++s;
    ++G->pos;
  }
  return 1;
}

YY_LOCAL(int) yymatchClass(GREG *G, unsigned char *bits, char *cclass)
{
  int c;
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  c= (unsigned char)G->buf[G->pos];
  if (bits[c >> 3] & (1 << (c & 7))) {
#ifdef YY_DEBUG
    if (G->buf[G->pos]) {
      yyprintfv((stderr, "  ok   yymatchClass [%s]", cclass));
      yyprintfvGcontext;
      yyprintfv((stderr, "\n"));
    } else {
      yyprintfv((stderr, "  ok   yymatchClass [%s] @ \"\"\n", cclass));
    }
#endif
    ++G->pos;
    return 1;
  }
  yyprintfv((stderr, "  fail yymatchClass [%s]", cclass));
  yyprintfvGcontext;
  yyprintfv((stderr, "\n"));
  return 0;
}

YY_LOCAL(void) yyDo(GREG *G, yyaction action, int begin, int end, const char *name)
{
  while (G->thunkpos >= G->thunkslen) {
    G->thunkslen *= 2;
    G->thunks= (yythunk*)YY_REALLOC(G->thunks, sizeof(yythunk) * G->thunkslen, G->data);
  }
  G->thunks[G->thunkpos].begin=  begin;
  G->thunks[G->thunkpos].end=    end;
  G->thunks[G->thunkpos].action= action;
  G->thunks[G->thunkpos].name=   name;
  ++G->thunkpos;
}

YY_LOCAL(int) yyText(GREG *G, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else {
    while (G->textlen < (yyleng + 1)) {
      G->textlen *= 2;
      G->text= (char*)YY_REALLOC(G->text, G->textlen, G->data);
    }
    memcpy(G->text, G->buf + begin, yyleng);
  }
  G->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(GREG *G)
{
  int pos;
  for (pos= 0;  pos < G->thunkpos;  ++pos) {
    yythunk *thunk= &G->thunks[pos];
    int yyleng= thunk->end ? yyText(G, thunk->begin, thunk->end) : thunk->begin;
    yyprintfv((stderr, "DO [%d] %s %d", pos, thunk->name, thunk->begin));
    yyprintfvTcontext(G->text);
    yyprintfv((stderr, "\n"));
    thunk->action(G, G->text, yyleng, thunk, G->data);
  }
  G->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(GREG *G)
{
  if ((G->limit -= G->pos)) {
    memmove(G->buf, G->buf + G->pos, G->limit);
  }
  G->offset += G->pos;
  G->begin -= G->pos;
  G->end -= G->pos;
  G->pos= G->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(GREG *G, int tp0)
{
  if (tp0) {
    fprintf(stderr, "accept denied at %d\n", tp0);
    return 0;
  }
  else {
    yyDone(G);
    yyCommit(G);
  }
  return 1;
}

YY_LOCAL(void) yyPush(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)	{
  yyprintfv((stderr, "yyPush %d\n", count));
  size_t off = (G->val - G->vals) + count;
  if (off > G->valslen) {
    while (G->valslen < off + 1)
      G->valslen *= 2;
    G->vals= (YYSTYPE*)YY_REALLOC((void *)G->vals, sizeof(YYSTYPE) * G->valslen, G->data);
    G->val= G->vals + off;
  } else {
    G->val += count;
  }
}
YY_LOCAL(void) yyPop(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR) {
  yyprintfv((stderr, "yyPop %d\n", count));
  G->val -= count;
}
YY_LOCAL(void) yySet(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)	{
#ifdef YY_SET
  YY_SET(G,text,count,thunk,YY_XVAR);
#else
  yyprintf((stderr, "%s %d %p\n", thunk->name, count, (void *)yy));
  G->val[count]= yy;
#endif
}

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(G, yythunkpos0)

YY_RULE(int) yy_end_of_line(GREG *G); /* 38 */
YY_RULE(int) yy_comment(GREG *G); /* 37 */
YY_RULE(int) yy_space(GREG *G); /* 36 */
YY_RULE(int) yy_braces(GREG *G); /* 35 */
YY_RULE(int) yy_range(GREG *G); /* 34 */
YY_RULE(int) yy_char(GREG *G); /* 33 */
YY_RULE(int) yy_END(GREG *G); /* 32 */
YY_RULE(int) yy_BEGIN(GREG *G); /* 31 */
YY_RULE(int) yy_DOT(GREG *G); /* 30 */
YY_RULE(int) yy_class(GREG *G); /* 29 */
YY_RULE(int) yy_literal(GREG *G); /* 28 */
YY_RULE(int) yy_CLOSE(GREG *G); /* 27 */
YY_RULE(int) yy_OPEN(GREG *G); /* 26 */
YY_RULE(int) yy_COLON(GREG *G); /* 25 */
YY_RULE(int) yy_PLUS(GREG *G); /* 24 */
YY_RULE(int) yy_STAR(GREG *G); /* 23 */
YY_RULE(int) yy_QUESTION(GREG *G); /* 22 */
YY_RULE(int) yy_primary(GREG *G); /* 21 */
YY_RULE(int) yy_NOT(GREG *G); /* 20 */
YY_RULE(int) yy_suffix(GREG *G); /* 19 */
YY_RULE(int) yy_AND(GREG *G); /* 18 */
YY_RULE(int) yy_action(GREG *G); /* 17 */
YY_RULE(int) yy_TILDE(GREG *G); /* 16 */
YY_RULE(int) yy_prefix(GREG *G); /* 15 */
YY_RULE(int) yy_error(GREG *G); /* 14 */
YY_RULE(int) yy_BAR(GREG *G); /* 13 */
YY_RULE(int) yy_sequence(GREG *G); /* 12 */
YY_RULE(int) yy_SEMICOLON(GREG *G); /* 11 */
YY_RULE(int) yy_expression(GREG *G); /* 10 */
YY_RULE(int) yy_EQUAL(GREG *G); /* 9 */
YY_RULE(int) yy_identifier(GREG *G); /* 8 */
YY_RULE(int) yy_RPERCENT(GREG *G); /* 7 */
YY_RULE(int) yy_end_of_file(GREG *G); /* 6 */
YY_RULE(int) yy_trailer(GREG *G); /* 5 */
YY_RULE(int) yy_definition(GREG *G); /* 4 */
YY_RULE(int) yy_declaration(GREG *G); /* 3 */
YY_RULE(int) yy__(GREG *G); /* 2 */
YY_RULE(int) yy_grammar(GREG *G); /* 1 */

YY_ACTION(void) yy_9_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_9_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makePredicate(\"YY_END\")); }\n"));
  {
    push(makePredicate("YY_END")); ;
  }
}
YY_ACTION(void) yy_8_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_8_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makePredicate(\"YY_BEGIN\")); }\n"));
  {
    push(makePredicate("YY_BEGIN")); ;
  }
}
YY_ACTION(void) yy_7_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_7_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeAction(yytext)); }\n"));
  {
    push(makeAction(yytext)); ;
  }
}
YY_ACTION(void) yy_6_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_6_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeDot()); }\n"));
  {
    push(makeDot()); ;
  }
}
YY_ACTION(void) yy_5_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_5_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeClass(yytext)); }\n"));
  {
    push(makeClass(yytext)); ;
  }
}
YY_ACTION(void) yy_4_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_4_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeString(yytext)); }\n"));
  {
    push(makeString(yytext)); ;
  }
}
YY_ACTION(void) yy_3_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_3_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeName(findRule(yytext, 0))); }\n"));
  {
    push(makeName(findRule(yytext, 0))); ;
  }
}
YY_ACTION(void) yy_2_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {Node *name= makeName(findRule(yytext, 0));  name->name.variable= pop();  push(name); }\n"));
  {
    Node *name= makeName(findRule(yytext, 0));  name->name.variable= pop();  push(name); ;
  }
}
YY_ACTION(void) yy_1_primary(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_primary"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeVariable(yytext)); }\n"));
  {
    push(makeVariable(yytext)); ;
  }
}
YY_ACTION(void) yy_3_suffix(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_3_suffix"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makePlus (pop())); }\n"));
  {
    push(makePlus (pop())); ;
  }
}
YY_ACTION(void) yy_2_suffix(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_suffix"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeStar (pop())); }\n"));
  {
    push(makeStar (pop())); ;
  }
}
YY_ACTION(void) yy_1_suffix(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_suffix"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeQuery(pop())); }\n"));
  {
    push(makeQuery(pop())); ;
  }
}
YY_ACTION(void) yy_3_prefix(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_3_prefix"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makePeekNot(pop())); }\n"));
  {
    push(makePeekNot(pop())); ;
  }
}
YY_ACTION(void) yy_2_prefix(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_prefix"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makePeekFor(pop())); }\n"));
  {
    push(makePeekFor(pop())); ;
  }
}
YY_ACTION(void) yy_1_prefix(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_prefix"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makePredicate(yytext)); }\n"));
  {
    push(makePredicate(yytext)); ;
  }
}
YY_ACTION(void) yy_1_error(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_error"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {push(makeError(pop(), yytext)); }\n"));
  {
    push(makeError(pop(), yytext)); ;
  }
}
YY_ACTION(void) yy_1_sequence(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_sequence"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {Node *f= pop();  push(Sequence_append(pop(), f)); }\n"));
  {
    Node *f= pop();  push(Sequence_append(pop(), f)); ;
  }
}
YY_ACTION(void) yy_1_expression(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_expression"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {Node *f= pop();  push(Alternate_append(pop(), f)); }\n"));
  {
    Node *f= pop();  push(Alternate_append(pop(), f)); ;
  }
}
YY_ACTION(void) yy_2_definition(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  #define s G->val[-1]
  yyprintf((stderr, "do yy_2_definition"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {Node *e= pop();  Rule_setExpression(pop(), e); }\n"));
  {
    Node *e= pop();  Rule_setExpression(pop(), e); ;
  }
  #undef s
}
YY_ACTION(void) yy_1_definition(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  #define s G->val[-1]
  yyprintf((stderr, "do yy_1_definition"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {if (push(beginRule(findRule(yytext, s)))->rule.expression)\n\
\t\t\t\t\t\t\t    fprintf(stderr, \"rule '%%s' redefined\\n\", yytext); }\n"));
  {
    if (push(beginRule(findRule(yytext, s)))->rule.expression)
							    fprintf(stderr, "rule '%s' redefined\n", yytext); ;
  }
  #undef s
}
YY_ACTION(void) yy_1_trailer(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_trailer"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {makeTrailer(yytext); }\n"));
  {
    makeTrailer(yytext); ;
  }
}
YY_ACTION(void) yy_1_declaration(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_declaration"));
  yyprintfvTcontext(yytext);
  yyprintf((stderr, "\n  {makeHeader(yytext); }\n"));
  {
    makeHeader(yytext); ;
  }
}

YY_RULE(int) yy_end_of_line(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "end_of_line"));
  {
    int yypos2= G->pos, yythunkpos2= G->thunkpos;
    if (!yymatchString(G, "\r\n")) goto l3;
    goto l2;
    l3:
    G->pos= yypos2; G->thunkpos= yythunkpos2;
    if (!yymatchChar(G, '\n')) goto l4;
    goto l2;
    l4:
    G->pos= yypos2; G->thunkpos= yythunkpos2;
    if (!yymatchChar(G, '\r')) goto l1;
  }

  l2:
  ;
  yyprintfvokrule("end_of_line");
  return 1;
  l1:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("end_of_line");
  return 0;
}
YY_RULE(int) yy_comment(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "comment"));
  if (!yymatchChar(G, '#')) goto l5;

  l6:
  {
    int yypos7= G->pos, yythunkpos7= G->thunkpos;
    {
      int yypos8= G->pos, yythunkpos8= G->thunkpos;
      if (!yy_end_of_line(G))       goto l8;
      goto l7;
      l8:
      G->pos= yypos8; G->thunkpos= yythunkpos8;
    }
    if (!yymatchDot(G)) goto l7;
    goto l6;
    l7:
    G->pos= yypos7; G->thunkpos= yythunkpos7;
  }
  if (!yy_end_of_line(G))   goto l5;
  yyprintfvokrule("comment");
  return 1;
  l5:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("comment");
  return 0;
}
YY_RULE(int) yy_space(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "space"));
  {
    int yypos10= G->pos, yythunkpos10= G->thunkpos;
    if (!yymatchChar(G, ' ')) goto l11;
    goto l10;
    l11:
    G->pos= yypos10; G->thunkpos= yythunkpos10;
    if (!yymatchChar(G, '\t')) goto l12;
    goto l10;
    l12:
    G->pos= yypos10; G->thunkpos= yythunkpos10;
    if (!yy_end_of_line(G))     goto l9;
  }

  l10:
  ;
  yyprintfvokrule("space");
  return 1;
  l9:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("space");
  return 0;
}
YY_RULE(int) yy_braces(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "braces"));
  {
    int yypos14= G->pos, yythunkpos14= G->thunkpos;
    if (!yymatchChar(G, '{')) goto l15;

    l16:
    {
      int yypos17= G->pos, yythunkpos17= G->thunkpos;
      if (!yy_braces(G))       goto l17;
      goto l16;
      l17:
      G->pos= yypos17; G->thunkpos= yythunkpos17;
    }
    if (!yymatchChar(G, '}')) goto l15;
    goto l14;
    l15:
    G->pos= yypos14; G->thunkpos= yythunkpos14;
    {
      int yypos18= G->pos, yythunkpos18= G->thunkpos;
      if (!yymatchChar(G, '}')) goto l18;
      goto l13;
      l18:
      G->pos= yypos18; G->thunkpos= yythunkpos18;
    }
    if (!yymatchDot(G)) goto l13;
  }

  l14:
  ;
  yyprintfokrule("braces");
  return 1;
  l13:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("braces");
  return 0;
}
YY_RULE(int) yy_range(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "range"));
  {
    int yypos20= G->pos, yythunkpos20= G->thunkpos;
    if (!yy_char(G))     goto l21;
    if (!yymatchChar(G, '-')) goto l21;
    if (!yy_char(G))     goto l21;
    goto l20;
    l21:
    G->pos= yypos20; G->thunkpos= yythunkpos20;
    if (!yy_char(G))     goto l19;
  }

  l20:
  ;
  yyprintfokrule("range");
  return 1;
  l19:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("range");
  return 0;
}
YY_RULE(int) yy_char(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "char"));
  {
    int yypos23= G->pos, yythunkpos23= G->thunkpos;
    if (!yymatchChar(G, '\\')) goto l24;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\204\040\000\000\000\000\000\070\146\100\124\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "-abefnrtv'\"\\[\\]\\\\")) goto l24;
    goto l23;
    l24:
    G->pos= yypos23; G->thunkpos= yythunkpos23;
    if (!yymatchChar(G, '\\')) goto l25;
    if (!yymatchChar(G, 'x')) goto l25;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-9A-Fa-f")) goto l25;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-9A-Fa-f")) goto l25;
    goto l23;
    l25:
    G->pos= yypos23; G->thunkpos= yythunkpos23;
    if (!yymatchChar(G, '\\')) goto l26;
    if (!yymatchChar(G, 'x')) goto l26;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-9A-Fa-f")) goto l26;
    goto l23;
    l26:
    G->pos= yypos23; G->thunkpos= yythunkpos23;
    if (!yymatchChar(G, '\\')) goto l27;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\017\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-3")) goto l27;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-7")) goto l27;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-7")) goto l27;
    goto l23;
    l27:
    G->pos= yypos23; G->thunkpos= yythunkpos23;
    if (!yymatchChar(G, '\\')) goto l28;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-7")) goto l28;
    {
      int yypos30= G->pos, yythunkpos30= G->thunkpos;
      if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "0-7")) goto l30;
      goto l29;
      l30:
      G->pos= yypos30; G->thunkpos= yythunkpos30;
    }

    l29:
    ;
    goto l23;
    l28:
    G->pos= yypos23; G->thunkpos= yythunkpos23;
    {
      int yypos31= G->pos, yythunkpos31= G->thunkpos;
      if (!yymatchChar(G, '\\')) goto l31;
      goto l22;
      l31:
      G->pos= yypos31; G->thunkpos= yythunkpos31;
    }
    if (!yymatchDot(G)) goto l22;
  }

  l23:
  ;
  yyprintfokrule("char");
  return 1;
  l22:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("char");
  return 0;
}
YY_RULE(int) yy_END(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "END"));
  if (!yymatchChar(G, '>')) goto l32;
  if (!yy__(G))   goto l32;
  yyprintfokrule("END");
  return 1;
  l32:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("END");
  return 0;
}
YY_RULE(int) yy_BEGIN(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "BEGIN"));
  if (!yymatchChar(G, '<')) goto l33;
  if (!yy__(G))   goto l33;
  yyprintfokrule("BEGIN");
  return 1;
  l33:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("BEGIN");
  return 0;
}
YY_RULE(int) yy_DOT(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "DOT"));
  if (!yymatchChar(G, '.')) goto l34;
  if (!yy__(G))   goto l34;
  yyprintfokrule("DOT");
  return 1;
  l34:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("DOT");
  return 0;
}
YY_RULE(int) yy_class(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "class"));
  if (!yymatchChar(G, '[')) goto l35;
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_BEGIN)) goto l35;
    #undef yytext
    #undef yyleng
  }


  l36:
  {
    int yypos37= G->pos, yythunkpos37= G->thunkpos;
    {
      int yypos38= G->pos, yythunkpos38= G->thunkpos;
      if (!yymatchChar(G, ']')) goto l38;
      goto l37;
      l38:
      G->pos= yypos38; G->thunkpos= yythunkpos38;
    }
    if (!yy_range(G))     goto l37;
    goto l36;
    l37:
    G->pos= yypos37; G->thunkpos= yythunkpos37;
  }
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_END)) goto l35;
    #undef yytext
    #undef yyleng
  }

  if (!yymatchChar(G, ']')) goto l35;
  if (!yy__(G))   goto l35;
  yyprintfokrule("class");
  return 1;
  l35:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("class");
  return 0;
}
YY_RULE(int) yy_literal(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "literal"));
  {
    int yypos40= G->pos, yythunkpos40= G->thunkpos;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "'")) goto l41;
    yyText(G, G->begin, G->end);
    {
      #define yytext G->text
      #define yyleng G->textlen
      if (!(YY_BEGIN)) goto l41;
      #undef yytext
      #undef yyleng
    }


    l42:
    {
      int yypos43= G->pos, yythunkpos43= G->thunkpos;
      {
        int yypos44= G->pos, yythunkpos44= G->thunkpos;
        if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "'")) goto l44;
        goto l43;
        l44:
        G->pos= yypos44; G->thunkpos= yythunkpos44;
      }
      if (!yy_char(G))       goto l43;
      goto l42;
      l43:
      G->pos= yypos43; G->thunkpos= yythunkpos43;
    }
    yyText(G, G->begin, G->end);
    {
      #define yytext G->text
      #define yyleng G->textlen
      if (!(YY_END)) goto l41;
      #undef yytext
      #undef yyleng
    }

    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "'")) goto l41;
    if (!yy__(G))     goto l41;
    goto l40;
    l41:
    G->pos= yypos40; G->thunkpos= yythunkpos40;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "\"")) goto l39;
    yyText(G, G->begin, G->end);
    {
      #define yytext G->text
      #define yyleng G->textlen
      if (!(YY_BEGIN)) goto l39;
      #undef yytext
      #undef yyleng
    }


    l45:
    {
      int yypos46= G->pos, yythunkpos46= G->thunkpos;
      {
        int yypos47= G->pos, yythunkpos47= G->thunkpos;
        if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "\"")) goto l47;
        goto l46;
        l47:
        G->pos= yypos47; G->thunkpos= yythunkpos47;
      }
      if (!yy_char(G))       goto l46;
      goto l45;
      l46:
      G->pos= yypos46; G->thunkpos= yythunkpos46;
    }
    yyText(G, G->begin, G->end);
    {
      #define yytext G->text
      #define yyleng G->textlen
      if (!(YY_END)) goto l39;
      #undef yytext
      #undef yyleng
    }

    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "\"")) goto l39;
    if (!yy__(G))     goto l39;
  }

  l40:
  ;
  yyprintfokrule("literal");
  return 1;
  l39:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("literal");
  return 0;
}
YY_RULE(int) yy_CLOSE(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "CLOSE"));
  if (!yymatchChar(G, ')')) goto l48;
  if (!yy__(G))   goto l48;
  yyprintfokrule("CLOSE");
  return 1;
  l48:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("CLOSE");
  return 0;
}
YY_RULE(int) yy_OPEN(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "OPEN"));
  if (!yymatchChar(G, '(')) goto l49;
  if (!yy__(G))   goto l49;
  yyprintfokrule("OPEN");
  return 1;
  l49:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("OPEN");
  return 0;
}
YY_RULE(int) yy_COLON(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "COLON"));
  if (!yymatchChar(G, ':')) goto l50;
  if (!yy__(G))   goto l50;
  yyprintfokrule("COLON");
  return 1;
  l50:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("COLON");
  return 0;
}
YY_RULE(int) yy_PLUS(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "PLUS"));
  if (!yymatchChar(G, '+')) goto l51;
  if (!yy__(G))   goto l51;
  yyprintfokrule("PLUS");
  return 1;
  l51:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("PLUS");
  return 0;
}
YY_RULE(int) yy_STAR(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "STAR"));
  if (!yymatchChar(G, '*')) goto l52;
  if (!yy__(G))   goto l52;
  yyprintfokrule("STAR");
  return 1;
  l52:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("STAR");
  return 0;
}
YY_RULE(int) yy_QUESTION(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "QUESTION"));
  if (!yymatchChar(G, '?')) goto l53;
  if (!yy__(G))   goto l53;
  yyprintfokrule("QUESTION");
  return 1;
  l53:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("QUESTION");
  return 0;
}
YY_RULE(int) yy_primary(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "primary"));
  {
    int yypos55= G->pos, yythunkpos55= G->thunkpos;
    if (!yy_identifier(G))     goto l56;
    yyDo(G, yy_1_primary, G->begin, G->end, "yy_1_primary");
    if (!yy_COLON(G))     goto l56;
    if (!yy_identifier(G))     goto l56;
    {
      int yypos57= G->pos, yythunkpos57= G->thunkpos;
      if (!yy_EQUAL(G))       goto l57;
      goto l56;
      l57:
      G->pos= yypos57; G->thunkpos= yythunkpos57;
    }
    yyDo(G, yy_2_primary, G->begin, G->end, "yy_2_primary");
    goto l55;
    l56:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_identifier(G))     goto l58;
    {
      int yypos59= G->pos, yythunkpos59= G->thunkpos;
      if (!yy_EQUAL(G))       goto l59;
      goto l58;
      l59:
      G->pos= yypos59; G->thunkpos= yythunkpos59;
    }
    yyDo(G, yy_3_primary, G->begin, G->end, "yy_3_primary");
    goto l55;
    l58:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_OPEN(G))     goto l60;
    if (!yy_expression(G))     goto l60;
    if (!yy_CLOSE(G))     goto l60;
    goto l55;
    l60:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_literal(G))     goto l61;
    yyDo(G, yy_4_primary, G->begin, G->end, "yy_4_primary");
    goto l55;
    l61:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_class(G))     goto l62;
    yyDo(G, yy_5_primary, G->begin, G->end, "yy_5_primary");
    goto l55;
    l62:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_DOT(G))     goto l63;
    yyDo(G, yy_6_primary, G->begin, G->end, "yy_6_primary");
    goto l55;
    l63:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_action(G))     goto l64;
    yyDo(G, yy_7_primary, G->begin, G->end, "yy_7_primary");
    goto l55;
    l64:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_BEGIN(G))     goto l65;
    yyDo(G, yy_8_primary, G->begin, G->end, "yy_8_primary");
    goto l55;
    l65:
    G->pos= yypos55; G->thunkpos= yythunkpos55;
    if (!yy_END(G))     goto l54;
    yyDo(G, yy_9_primary, G->begin, G->end, "yy_9_primary");
  }

  l55:
  ;
  yyprintfokrule("primary");
  return 1;
  l54:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("primary");
  return 0;
}
YY_RULE(int) yy_NOT(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "NOT"));
  if (!yymatchChar(G, '!')) goto l66;
  if (!yy__(G))   goto l66;
  yyprintfokrule("NOT");
  return 1;
  l66:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("NOT");
  return 0;
}
YY_RULE(int) yy_suffix(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "suffix"));
  if (!yy_primary(G))   goto l67;
  {
    int yypos69= G->pos, yythunkpos69= G->thunkpos;
    {
      int yypos70= G->pos, yythunkpos70= G->thunkpos;
      if (!yy_QUESTION(G))       goto l71;
      yyDo(G, yy_1_suffix, G->begin, G->end, "yy_1_suffix");
      goto l70;
      l71:
      G->pos= yypos70; G->thunkpos= yythunkpos70;
      if (!yy_STAR(G))       goto l72;
      yyDo(G, yy_2_suffix, G->begin, G->end, "yy_2_suffix");
      goto l70;
      l72:
      G->pos= yypos70; G->thunkpos= yythunkpos70;
      if (!yy_PLUS(G))       goto l69;
      yyDo(G, yy_3_suffix, G->begin, G->end, "yy_3_suffix");
    }

    l70:
    ;
    goto l68;
    l69:
    G->pos= yypos69; G->thunkpos= yythunkpos69;
  }

  l68:
  ;
  yyprintfokrule("suffix");
  return 1;
  l67:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("suffix");
  return 0;
}
YY_RULE(int) yy_AND(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "AND"));
  if (!yymatchChar(G, '&')) goto l73;
  if (!yy__(G))   goto l73;
  yyprintfokrule("AND");
  return 1;
  l73:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("AND");
  return 0;
}
YY_RULE(int) yy_action(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "action"));
  if (!yymatchChar(G, '{')) goto l74;
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_BEGIN)) goto l74;
    #undef yytext
    #undef yyleng
  }


  l75:
  {
    int yypos76= G->pos, yythunkpos76= G->thunkpos;
    if (!yy_braces(G))     goto l76;
    goto l75;
    l76:
    G->pos= yypos76; G->thunkpos= yythunkpos76;
  }
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_END)) goto l74;
    #undef yytext
    #undef yyleng
  }

  if (!yymatchChar(G, '}')) goto l74;
  if (!yy__(G))   goto l74;
  yyprintfokrule("action");
  return 1;
  l74:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("action");
  return 0;
}
YY_RULE(int) yy_TILDE(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "TILDE"));
  if (!yymatchChar(G, '~')) goto l77;
  if (!yy__(G))   goto l77;
  yyprintfokrule("TILDE");
  return 1;
  l77:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("TILDE");
  return 0;
}
YY_RULE(int) yy_prefix(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "prefix"));
  {
    int yypos79= G->pos, yythunkpos79= G->thunkpos;
    if (!yy_AND(G))     goto l80;
    if (!yy_action(G))     goto l80;
    yyDo(G, yy_1_prefix, G->begin, G->end, "yy_1_prefix");
    goto l79;
    l80:
    G->pos= yypos79; G->thunkpos= yythunkpos79;
    if (!yy_AND(G))     goto l81;
    if (!yy_suffix(G))     goto l81;
    yyDo(G, yy_2_prefix, G->begin, G->end, "yy_2_prefix");
    goto l79;
    l81:
    G->pos= yypos79; G->thunkpos= yythunkpos79;
    if (!yy_NOT(G))     goto l82;
    if (!yy_suffix(G))     goto l82;
    yyDo(G, yy_3_prefix, G->begin, G->end, "yy_3_prefix");
    goto l79;
    l82:
    G->pos= yypos79; G->thunkpos= yythunkpos79;
    if (!yy_suffix(G))     goto l78;
  }

  l79:
  ;
  yyprintfokrule("prefix");
  return 1;
  l78:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("prefix");
  return 0;
}
YY_RULE(int) yy_error(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "error"));
  if (!yy_prefix(G))   goto l83;
  {
    int yypos85= G->pos, yythunkpos85= G->thunkpos;
    if (!yy_TILDE(G))     goto l85;
    if (!yy_action(G))     goto l85;
    yyDo(G, yy_1_error, G->begin, G->end, "yy_1_error");
    goto l84;
    l85:
    G->pos= yypos85; G->thunkpos= yythunkpos85;
  }

  l84:
  ;
  yyprintfokrule("error");
  return 1;
  l83:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("error");
  return 0;
}
YY_RULE(int) yy_BAR(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "BAR"));
  if (!yymatchChar(G, '|')) goto l86;
  if (!yy__(G))   goto l86;
  yyprintfokrule("BAR");
  return 1;
  l86:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("BAR");
  return 0;
}
YY_RULE(int) yy_sequence(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "sequence"));
  if (!yy_error(G))   goto l87;

  l88:
  {
    int yypos89= G->pos, yythunkpos89= G->thunkpos;
    if (!yy_error(G))     goto l89;
    yyDo(G, yy_1_sequence, G->begin, G->end, "yy_1_sequence");
    goto l88;
    l89:
    G->pos= yypos89; G->thunkpos= yythunkpos89;
  }
  yyprintfokrule("sequence");
  return 1;
  l87:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("sequence");
  return 0;
}
YY_RULE(int) yy_SEMICOLON(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "SEMICOLON"));
  if (!yymatchChar(G, ';')) goto l90;
  if (!yy__(G))   goto l90;
  yyprintfokrule("SEMICOLON");
  return 1;
  l90:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("SEMICOLON");
  return 0;
}
YY_RULE(int) yy_expression(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "expression"));
  if (!yy_sequence(G))   goto l91;

  l92:
  {
    int yypos93= G->pos, yythunkpos93= G->thunkpos;
    if (!yy_BAR(G))     goto l93;
    if (!yy_sequence(G))     goto l93;
    yyDo(G, yy_1_expression, G->begin, G->end, "yy_1_expression");
    goto l92;
    l93:
    G->pos= yypos93; G->thunkpos= yythunkpos93;
  }
  yyprintfokrule("expression");
  return 1;
  l91:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("expression");
  return 0;
}
YY_RULE(int) yy_EQUAL(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "EQUAL"));
  if (!yymatchChar(G, '=')) goto l94;
  if (!yy__(G))   goto l94;
  yyprintfokrule("EQUAL");
  return 1;
  l94:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("EQUAL");
  return 0;
}
YY_RULE(int) yy_identifier(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "identifier"));
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_BEGIN)) goto l95;
    #undef yytext
    #undef yyleng
  }

  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\040\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "-a-zA-Z_")) goto l95;

  l96:
  {
    int yypos97= G->pos, yythunkpos97= G->thunkpos;
    if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000", "-a-zA-Z_0-9")) goto l97;
    goto l96;
    l97:
    G->pos= yypos97; G->thunkpos= yythunkpos97;
  }
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_END)) goto l95;
    #undef yytext
    #undef yyleng
  }

  if (!yy__(G))   goto l95;
  yyprintfokrule("identifier");
  return 1;
  l95:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("identifier");
  return 0;
}
YY_RULE(int) yy_RPERCENT(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "RPERCENT"));
  if (!yymatchString(G, "%}")) goto l98;
  if (!yy__(G))   goto l98;
  yyprintfokrule("RPERCENT");
  return 1;
  l98:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("RPERCENT");
  return 0;
}
YY_RULE(int) yy_end_of_file(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "end_of_file"));
  {
    int yypos100= G->pos, yythunkpos100= G->thunkpos;
    if (!yymatchDot(G)) goto l100;
    goto l99;
    l100:
    G->pos= yypos100; G->thunkpos= yythunkpos100;
  }
  yyprintfvokrule("end_of_file");
  return 1;
  l99:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("end_of_file");
  return 0;
}
YY_RULE(int) yy_trailer(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "trailer"));
  if (!yymatchString(G, "%%")) goto l101;
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_BEGIN)) goto l101;
    #undef yytext
    #undef yyleng
  }


  l102:
  {
    int yypos103= G->pos, yythunkpos103= G->thunkpos;
    if (!yymatchDot(G)) goto l103;
    goto l102;
    l103:
    G->pos= yypos103; G->thunkpos= yythunkpos103;
  }
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_END)) goto l101;
    #undef yytext
    #undef yyleng
  }

  yyDo(G, yy_1_trailer, G->begin, G->end, "yy_1_trailer");
  yyprintfokrule("trailer");
  return 1;
  l101:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("trailer");
  return 0;
}
YY_RULE(int) yy_definition(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyDo(G, yyPush, 1, 0, "yyPush");
  yyprintfv((stderr, "%s\n", "definition"));
  if (!yy_identifier(G))   goto l104;
  yyDo(G, yySet, -1, 0, "yySet identifier");
  yyDo(G, yy_1_definition, G->begin, G->end, "yy_1_definition");
  if (!yy_EQUAL(G))   goto l104;
  if (!yy_expression(G))   goto l104;
  yyDo(G, yy_2_definition, G->begin, G->end, "yy_2_definition");
  {
    int yypos106= G->pos, yythunkpos106= G->thunkpos;
    if (!yy_SEMICOLON(G))     goto l106;
    goto l105;
    l106:
    G->pos= yypos106; G->thunkpos= yythunkpos106;
  }

  l105:
  ;
  yyprintfokrule("definition");
  yyDo(G, yyPop, 1, 0, "yyPop");
  return 1;
  l104:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("definition");
  return 0;
}
YY_RULE(int) yy_declaration(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "declaration"));
  if (!yymatchString(G, "%{")) goto l107;
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_BEGIN)) goto l107;
    #undef yytext
    #undef yyleng
  }


  l108:
  {
    int yypos109= G->pos, yythunkpos109= G->thunkpos;
    {
      int yypos110= G->pos, yythunkpos110= G->thunkpos;
      if (!yymatchString(G, "%}")) goto l110;
      goto l109;
      l110:
      G->pos= yypos110; G->thunkpos= yythunkpos110;
    }
    if (!yymatchDot(G)) goto l109;
    goto l108;
    l109:
    G->pos= yypos109; G->thunkpos= yythunkpos109;
  }
  yyText(G, G->begin, G->end);
  {
    #define yytext G->text
    #define yyleng G->textlen
    if (!(YY_END)) goto l107;
    #undef yytext
    #undef yyleng
  }

  if (!yy_RPERCENT(G))   goto l107;
  yyDo(G, yy_1_declaration, G->begin, G->end, "yy_1_declaration");
  yyprintfokrule("declaration");
  return 1;
  l107:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("declaration");
  return 0;
}
YY_RULE(int) yy__(GREG *G)
{  yyprintfv((stderr, "%s\n", "_"));

  l112:
  {
    int yypos113= G->pos, yythunkpos113= G->thunkpos;
    {
      int yypos114= G->pos, yythunkpos114= G->thunkpos;
      if (!yy_space(G))       goto l115;
      goto l114;
      l115:
      G->pos= yypos114; G->thunkpos= yythunkpos114;
      if (!yy_comment(G))       goto l113;
    }

    l114:
    ;
    goto l112;
    l113:
    G->pos= yypos113; G->thunkpos= yythunkpos113;
  }
  yyprintfvokrule("_");
  return 1;
}
YY_RULE(int) yy_grammar(GREG *G)
{
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintfv((stderr, "%s\n", "grammar"));
  if (!yy__(G))   goto l116;
  {
    int yypos119= G->pos, yythunkpos119= G->thunkpos;
    if (!yy_declaration(G))     goto l120;
    goto l119;
    l120:
    G->pos= yypos119; G->thunkpos= yythunkpos119;
    if (!yy_definition(G))     goto l116;
  }

  l119:
  ;

  l117:
  {
    int yypos118= G->pos, yythunkpos118= G->thunkpos;
    {
      int yypos121= G->pos, yythunkpos121= G->thunkpos;
      if (!yy_declaration(G))       goto l122;
      goto l121;
      l122:
      G->pos= yypos121; G->thunkpos= yythunkpos121;
      if (!yy_definition(G))       goto l118;
    }

    l121:
    ;
    goto l117;
    l118:
    G->pos= yypos118; G->thunkpos= yythunkpos118;
  }
  {
    int yypos124= G->pos, yythunkpos124= G->thunkpos;
    if (!yy_trailer(G))     goto l124;
    goto l123;
    l124:
    G->pos= yypos124; G->thunkpos= yythunkpos124;
  }

  l123:
  ;
  if (!yy_end_of_file(G))   goto l116;
  yyprintfokrule("grammar");
  return 1;
  l116:
  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintfvfailrule("grammar");
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(GREG *G);

YY_PARSE(int) YY_NAME(parse_from)(GREG *G, yyrule yystart)
{
  int yyok;
  if (!G->buflen)
    {
      G->buflen= YY_BUFFER_START_SIZE;
      G->buf= (char*)YY_ALLOC(G->buflen, G->data);
      G->textlen= YY_BUFFER_START_SIZE;
      G->text= (char*)YY_ALLOC(G->textlen, G->data);
      G->thunkslen= YY_STACK_SIZE;
      G->thunks= (yythunk*)YY_ALLOC(sizeof(yythunk) * G->thunkslen, G->data);
      G->valslen= YY_STACK_SIZE;
      G->vals= (YYSTYPE*)YY_ALLOC(sizeof(YYSTYPE) * G->valslen, G->data);
      G->begin= G->end= G->pos= G->limit= G->thunkpos= 0;
    }
  G->pos = 0;
  G->begin= G->end= G->pos;
  G->thunkpos= 0;
  G->val= G->vals;
  yyok= yystart(G);
  if (yyok) yyDone(G);
  yyCommit(G);
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
}

YY_PARSE(int) YY_NAME(parse)(GREG *G)
{
  return YY_NAME(parse_from)(G, yy_grammar);
}

YY_PARSE(GREG *) YY_NAME(parse_new)(YY_XTYPE data)
{
  GREG *G= (GREG *)YY_CALLOC(1, sizeof(GREG), G->data);
  G->data= data;
  G->input= stdin;
  G->lineno= 1;
  G->filename= "-";
  return G;
}
YY_PARSE(void) YY_NAME(init)(GREG *G)
{
  memset(G, 0, sizeof(GREG));
  G->input= stdin;
  G->lineno= 1;
  G->filename= "-";
}

YY_PARSE(void) YY_NAME(deinit)(GREG *G)
{
    if (G->buf) YY_FREE(G->buf);
    if (G->text) YY_FREE(G->text);
    if (G->thunks) YY_FREE(G->thunks);
    if (G->vals) YY_FREE((void*)G->vals);
}
YY_PARSE(void) YY_NAME(parse_free)(GREG *G)
{
  YY_NAME(deinit)(G);
  YY_FREE(G);
}

#endif


void makeHeader(char *text)
{
  Header *header= (Header *)malloc(sizeof(Header));
  header->text= strdup(text);
  header->next= headers;
  headers= header;
}

void makeTrailer(char *text)
{
  trailer= strdup(text);
}

static void version(char *name)
{
  printf("%s version %d.%d.%d\n", name, GREG_MAJOR, GREG_MINOR, GREG_LEVEL);
}

static void usage(char *name)
{
  version(name);
  fprintf(stderr, "usage: %s [<option>...] [<file>...]\n", name);
  fprintf(stderr, "where <option> can be\n");
  fprintf(stderr, "  -h          print this help information\n");
  fprintf(stderr, "  -o <ofile>  write output to <ofile>\n");
  fprintf(stderr, "  -v          be verbose\n");
#ifdef YY_DEBUG
  fprintf(stderr, "  -vv         be more verbose\n");
#endif
  fprintf(stderr, "  -V          print version number and exit\n");
  fprintf(stderr, "if no <file> is given, input is read from stdin\n");
  fprintf(stderr, "if no <ofile> is given, output is written to stdout\n");
  exit(1);
}

int main(int argc, char **argv)
{
  GREG *G;
  Node *n;
  int   c;

  output= stdout;

  while (-1 != (c= getopt(argc, argv, "Vho:v")))
    {
      switch (c)
	{
	case 'V':
	  version(basename(argv[0]));
	  exit(0);

	case 'h':
	  usage(basename(argv[0]));
	  break;

	case 'o':
	  if (!(output= fopen(optarg, "w")))
	    {
	      perror(optarg);
	      exit(1);
	    }
	  break;

	case 'v':
	  verboseFlag++;
	  break;

	default:
	  fprintf(stderr, "for usage try: %s -h\n", argv[0]);
	  exit(1);
	}
    }
  argc -= optind;
  argv += optind;

  G = yyparse_new(NULL);
#ifdef YY_DEBUG
  if (verboseFlag > 0) { yydebug = YYDEBUG_PARSE;
    if (verboseFlag > 1) yydebug = YYDEBUG_PARSE + YYDEBUG_VERBOSE;
  }
#endif

  if (argc)
    {
      for (;  argc;  --argc, ++argv)
	{
	  if (strcmp(*argv, "-"))
	    {
	      G->filename= *argv;
	      if (!(G->input= fopen(G->filename, "r")))
		{
		  perror(G->filename);
		  exit(1);
		}
	    }
	  if (!yyparse(G))
	    YY_ERROR("syntax error");
	  if (G->input != stdin)
	    fclose(G->input);
	}
    }
  else
    if (!yyparse(G))
      YY_ERROR("syntax error");
  yyparse_free(G);

  if (verboseFlag)
    for (n= rules;  n;  n= n->any.next)
      Rule_print(n);

  Rule_compile_c_header();

  while (headers) {
    Header *tmp = headers;
    fprintf(output, "%s\n", headers->text);
    free(headers->text);
    tmp= headers->next;
    free(headers);
    headers= tmp;
  }

  if (rules) {
    Rule_compile_c(rules);
    freeRules();
  }

  if (trailer) {
    fputs(trailer, output);
    fputs("\n", output);
    free(trailer);
  }
  else
    fputs(deftrailer, output);

  return 0;
}

